name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Deploy
        run: |
          cd /home/ubuntu/actions-runner/_work/stage/stage || exit
          docker-compose down
          docker-compose up -d --build
        working-directory: /home/ubuntu/actions-runner/_work/stage/stage
